Add operator and quotes to the AX_PYTHON_DEVEL parameter
The operator is required and the quotes are needed to protect PYTHON_VERSION.

See-also: https://www.gnu.org/software/autoconf-archive/ax_python_devel.html
Reverts: commit 1c42bb98bf7d3347fe81566b41916276b78cc022
Reapply: commit 426799f1572c5df266b1ecd882cd776c8496a97c
Fixes: commit 1e4f3d37fdad14a7b3841e82beeead7c1da6a255
Fixes:
checking whether to build the libpst python interface... yes
checking for python build information...
checking for python3.7... python3.7
checking for main in -lpython3.7... no
checking for main in -lpython3.7m... yes
  results of the Python check:
    Binary:      python3.7
    Library:     python3.7m
    Include Dir: /usr/include/python3.7m
checking for python3.7... /usr/bin/python3.7
checking for a version of Python >= '2.1.0'... yes
checking for a version of Python 3.7...   File "<string>", line 1
    import sys;                         ver = sys.version.split ()[0];                  print (ver 3.7)
                                                                  ^
SyntaxError: invalid syntax
no
configure: error: this package requires Python 3.7.
If you have it installed, but it isn't the default Python
interpreter in your system path, please pass the PYTHON_VERSION
variable to configure. See ``configure --help'' for reference.